### ISSUE TITLE
Deprecation Warning Issued: "Deprecated since v0.6.0!.."

### ISSUE THREAD

**Issue by taifu** [pyexcel/pyexcel-io#104]
https://github.com/pyexcel/pyexcel-io/blob/9d70e9703754282fb17f0e970d73078bf2e416a2/pyexcel_io/book.py#L32

Using pyexcel.get_book always raises a Deprecation Warning. Why? How have I to open a file?

pyexcel==0.5.15
pyexcel-io==0.6.3
pyexcel-ods==0.5.6
pyexcel-xls==0.5.9
pyexcel-xlsx==0.5.8

**Comment by chfw** [comment]
Hi, it means pyexcel-io 0.6.x had plugin interface updated. Although backward compatibility is insured, you are advised to upgrade its plugins to 0.6.x. 

Here is the change log:
https://github.com/pyexcel/pyexcel-io/blob/dev/CHANGELOG.rst#061---7102020

**Comment by chfw** [comment]
And here is the table:

http://io.pyexcel.org/en/latest/#id6

**Comment by taifu** [comment]
These where the plugin version installed:
```
pyexcel==0.5.15
pyexcel-io==0.6.3
pyexcel-ods==0.5.6
pyexcel-xls==0.5.9
pyexcel-xlsx==0.5.8
```

All of those seems to be more than enough respect the table.
I updated two of them and the warning disappeared:
```
pyexcel==0.5.15
pyexcel-io==0.6.3
pyexcel-ods==0.5.6
pyexcel-xls==0.6.1
pyexcel-xlsx==0.6.0
```

**Comment by chfw** [comment]
It means your code does not handle ods file type yet.

**Comment by taifu** [comment]
Updating the plugins solved the warning.

**Comment by taifu** [comment]
> It means your code does not handle ods file type yet.

Just to be sure I updated all of them (I use the ods but I do not test them now):

```
pyexcel==0.6.5
pyexcel-io==0.6.3
pyexcel-ods==0.6.0
pyexcel-xls==0.6.1
pyexcel-xlsx==0.6.0
```

**Comment by chfw** [comment]
Oh you may want to upgrade pyexcel to 0.6.5 if you use database queryset. If not, pyexcel 0.5.15 is fine.

**Comment by chfw** [comment]
https://github.com/pyexcel/pyexcel/blob/dev/CHANGELOG.rst#065---8102020

**Comment by chfw** [comment]
Case closed! thanks for raising the issue, which helps the interaction between pyexcel and pyexcel community.
