### ISSUE TITLE
"Deprecated since v0.6.0" warning despite upgrade

### ISSUE THREAD

**Issue by Guillaume-Garrigos** [pyexcel/pyexcel-io#111]
Hi,

I am having a similar problem as in issue #104 : calling `pyexcel.get_book` to open an .ods file rises the warning `UserWarning: Deprecated since v0.6.0! Although backward compatibility is preserved, it is recommended to upgrade to get new features.`

It seems that issue #104 was solved after upgrading pyexcel and its plugins. I did the same, but the warning remains. I am missing something obvious?

pyexcel==0.6.7
pyexcel-io==0.6.5
pyexcel-ods==0.6.0
pyexcel-xls==0.7.0
pyexcel-xlsx==0.6.0

**Comment by chfw** [comment]
unless you had two Python environments, typically a system wide on and a virtual one. It is likely that your system one had old plugins but current virtual one had the lastest, hence pip freeze cannot spell out the problem.

**Comment by Guillaume-Garrigos** [comment]
I am not using a virtual environment, as far as I know I only have one Python environment on my system.

This being said, you mentionning `python freeze` made me think about giving it a look, and I noticed that there was an *other* pyexcel package that I forgot to update : `pyexcel-ods3`. After upgrading the warning was gone!

**Comment by chfw** [comment]
pyexcel-ods used to be made for python 2 and pyexcel-ods3 for python 3. Nowadays, both differ by their dependent library and as well as their license. so you can choose which one suits your license requirements and your need.
