### ISSUE TITLE
RemovedInDjango110Warning

### ISSUE THREAD

**Issue by girijasameera** [pyexcel/pyexcel-io#12]
I have been following the tutorial at http://django-excel.readthedocs.org/en/latest/
After,
python manage.py migrate
python manage.py runserver

I get the following warnings

C:\Python27\lib\site-packages\django\template\utils.py:37: RemovedInDjango110Warning: You haven't defined a TEMPLATES setting. You must do so before upgrading to Django 1.10. Otherwise Django will be unable to load templates.
  "unable to load templates.", RemovedInDjango110Warning)

C:\Users\Lenovo\django-excel\polls\urls.py:13: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^export/(.*)', views.export_data, name="export")

C:\Users\Lenovo\django-excel\mysite\urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^polls/', include('polls.urls'))

Please help. Thank you.

**Comment by chfw** [comment]
Looking at it. For future reference, could I also advise next issue related to django-excel to be raised in django-excel project? This is related to pyexcel-io only.

**Comment by girijasameera** [comment]
Ok will do.Thanks.

**Comment by chfw** [comment]
Django 1.10 is not released in pypy yet. Where to get it?

**Comment by girijasameera** [comment]
No idea.but it says  Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
 url(r'^polls/', include('polls.urls')) 

I wasn't sure what that means. Doing that will stop giving the warning.

**Comment by chfw** [comment]
transferring this issue to django-excel
