### ISSUE TITLE
object of type 'generator' has no attribute 'len'

### ISSUE THREAD

**Issue by serates** [pyexcel/pyexcel-io#13]
The changes in pyexcel-io/base.py in SheetReader.to_array to use yield to defer return till needed has led to an error with django_excel when trying to import a xlsx file. 

You should be able to reproduce this via trying to import a xlsx using pyexcel-xlsx and django_excel. This happen when pyexcel-io >= 0.0.9 is being used, and this was being run on a Python 2.7 environment if you are wondering.

**Comment by chfw** [comment]
what if you install pyexcel==0.2.0? The test [has passed](https://travis-ci.org/pyexcel/django-excel/jobs/102862031) with python 2.7

**Comment by serates** [comment]
Ah sorry about this, you are right it passes beautifuly using pyexcel 0.2.0. Is there anyway in the next release to update dependencies so that 0.2.0 is required? Granted we ran into this issue from a stupid not explicitly listing pyexcel in our dependencies. We used the requirements of django-excel and pyexcel-xlsx to determine what gets installed, and since we've been using this for so long pyexcel didn't seem to get updated.

**Comment by chfw** [comment]
Surely, I will do. In fact the latest django-execel 0.0.3 had this requirement chain -> pyexcel-webio 0.0.5 -> pyexcel 0.2.0 -> 0.1.0. In next release 0.0.4, dependency management will be centralized into one project, aiming to provide more accruate requirements for each pyexcel projects.

At last, thanks for using django-excel. There is no stupid question but silly software, which we can make better. Let me close this question. But feel free to raise issue if anything else pops up.

**Comment by serates** [comment]
Thank you so much for your prompt response, I and the rest of my team can't thank you enough for your work on django-excel and pyexcel.
