### ISSUE TITLE
DjangoBookWriter does not support batch_size

### ISSUE THREAD

**Issue by readflybird** [pyexcel/pyexcel-io#24]
In class DjangoBookWriter,  the open_content() method, the parameters keywords are ignored and thus there is no way we can pass in the batch_size. Besides, the create_sheet() method does not take care of batch_size, neither. Therefore there is no way we can do a batch insert through DjangoModelWriter.

**Comment by chfw** [comment]
It is true that 'batch_size' was not passed on and 'batch_size' controls the number of records being inserted at once. If not mentioned, [default batch_size 999 is used](https://docs.djangoproject.com/en/1.10/ref/models/querysets/#bulk-create). However, it won't block batch insertion. 

Please check for [database error](https://github.com/pyexcel/pyexcel-io/blob/master/pyexcel_io/database/django.py#L74) such as integrity error during bulk import. Once there is any exception, it will default to 'snail' alike insertion - one record at a time, skipping offending ones.

**Comment by readflybird** [comment]
Thanks for the quick fix. Is there any plan that to merge this change into a release branch?

**Comment by chfw** [comment]
by default, I would release it with v0.3.0, which should be released by the end of this year. Can you wait for it? Otherwise, I can do a quick release as v0.2.6.

**Comment by chfw** [comment]
released in v0.2.6 via pipit

**Comment by readflybird** [comment]
Thanks a lot for the response! I have tried out the new version and it works great!
