### ISSUE TITLE
Incompatible with flake8 version 3.2.0 ?

### ISSUE THREAD

**Issue by Torniojaws** [pyexcel/pyexcel-io#27]
With pyexcel-io version 0.2.6, flake8 3.2.0 passes just fine.

With pyexcel-io version 0.3.0, flake8 3.2.0 throws the below. The only difference in dependencies is pyexcel-io version, and it is repeatable.

> Traceback (most recent call last):
>   File "manage.py", line 126, in <module>
>     manager.run()
>   File "C:\Python34\lib\site-packages\flask_script\__init__.py", line 412, in run
>     result = self.handle(sys.argv[0], sys.argv[1:])
>   File "C:\Python34\lib\site-packages\flask_script\__init__.py", line 383, in handle
>     res = handle(*args, **config)
>   File "C:\Python34\lib\site-packages\flask_script\__init__.py", line 156, in __call__
>     app = app(**kwargs)
>   File "manage.py", line 24, in my_create_app
>     return create_app(register_db=False)
>   File "C:\ccc\Projects\xxx\xxx\factory.py", line 27, in create_app
>     register_models(app)
>   File "C:\ccc\Projects\xxx\xxx\factory.py", line 114, in register_models
>     "xxx.apps.{}.models".format(model)
>   File "C:\Python34\lib\importlib\__init__.py", line 109, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1129, in _exec
>   File "<frozen importlib._bootstrap>", line 1471, in exec_module
>   File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
>   File "C:\ccc\Projects\xxx\xxx\apps\mask\models.py", line 9, in <module>
>     from xxx.libs.xslt import exports
>   File "C:\ccc\Projects\xxx\xxx\libs\xslt\exports.py", line 5, in <module>
>     from pyexcel_xls import save_data
>   File "C:\Python34\lib\site-packages\pyexcel_xls\__init__.py", line 17, in <module>
>     from pyexcel_io.io import get_data as read_data, isstream, store_data as write_data
>   File "C:\Python34\lib\site-packages\pyexcel_io\__init__.py", line 35, in <module>
>     pre_register(p, module_name)
>   File "C:\Python34\lib\site-packages\pyexcel_io\manager.py", line 27, in pre_register
>     library_import_path = "%s.%s" % (module_name, library_meta['submodule'])
> TypeError: <flask_script.Manager object at 0x0000000002921E80>: string indices must be integers

Here's the Flask versions, since it mentions flask:

> # Flask
> Flask==0.10.1
> Flask-Admin==1.4.2
> Flask-Classy==0.6.10
> Flask-Login==0.3.2
> Jinja2==2.8
> Werkzeug==0.11.9
> 
> # Management script
> Flask-Script
> 
> # Database
> SQLAlchemy==1.0.14
> PyMySQL==0.7.3
> Flask-SQLAlchemy==2.1
> Flask-Migrate==2.0.0
> 
> # Debug toolbar
> Flask-DebugToolbar==0.10.0
> 
> # Forms
> Flask-WTF==0.13
> WTForms==2.1

**Comment by chfw** [comment]
what about other pyexcel plugins? those plugins should be updated to 0.3.0 as well.

**Comment by chfw** [comment]
https://github.com/pyexcel/pyexcel-io/commit/7aaaccb51ecba2b01288339b3e9ae59905d0c705 addresses the potential use case: pip install pyexcel-io[xls]
