### ISSUE TITLE
No Byte order mark (BOM) when creating UTF8 CSV file

### ISSUE THREAD

**Issue by guysoft** [pyexcel/pyexcel-io#30]
A UTF-8 encoded [should include at the start a BOM to specify that its using UTF-8](https://en.wikipedia.org/wiki/Comma-separated_values#Standardization). There are several csv readers (I think also Microsoft excel) that look for that byte to determine if to read the csv as unicode. Its also [part of unicode(http://unicode.org/faq/utf_bom.html#bom2)

You can get the utf8 BOM like this:

    import codecs
    codecs.BOM_UTF8

You should see ``b'\xef\xbb\xbf'``.
This should be added to the start of a generated csv. If you could point me to where is located I can create a pull request.

Workaround I use now (in python3, where I have to use ``'\ufeff'`` because of how it opens a file):
```python
def add_utf8_bom(filename):
    with codecs.open(filename, 'r', 'utf-8') as f:
        content = f.read()
    with codecs.open(filename, 'w', 'utf-8') as f2:
        f2.write('\ufeff')
        f2.write(content)
```

**Comment by chfw** [comment]
Sure, PR is welcome. There are two places you will need to look at depending on python versions

For python 2, please look at https://github.com/pyexcel/pyexcel-io/blob/master/pyexcel_io/fileformat/_csv.py#L58. UnicodeWriter is the one. You may try to optimise it.

For python 3, please look at https://github.com/pyexcel/pyexcel-io/blob/master/pyexcel_io/fileformat/_csv.py#L197.

The success criteria(or test cases) are: 
1. pyexcel-io should also be able to read the resulting file, csv file with BOM header as well both in memory and physical file.
2. csv file without BOM header can be read out too 
2. an excel book(having more than 1 sheet) could be saved to a memory stream and read it back.

**Comment by guysoft** [comment]
Do you have those tests written anywhere?

**Comment by chfw** [comment]
tests for item 2 exist but for 1 and 3 needs writing when the change is to be made.

**Comment by guysoft** [comment]
Can you provide a link to test reading? I want to now what to run so I don't develop the wrong thing.
Assume there is no BOM at the moment, I will extend it if needed.

**Comment by chfw** [comment]
Here is the test code for [reading normal csv](https://github.com/pyexcel/pyexcel-io/blob/master/tests/test_csv_book.py#L20). Please examine it if it suits your purpose. You can find all test codes under "tests" directory.

**Comment by guysoft** [comment]
Sorry I am not getting the time to come round to this.
However I can confirm that the BOM does make reading the CSV also a problem, the charecters are added to the end of the first column.

**Comment by guysoft** [comment]
Ok good and surprising news,
Its possible to read and write files with utf-8 bom when using ``utf-8-sig`` encoding like this:

Reading:
```python
records = pyexcel.get_records(file_name=csv_path, encoding="utf-8-sig")
```
Writing:
```python
pyexcel.save_as(array=sheet, dest_file_name=data_csv, dest_encoding="utf-8-sig")
```

I am not sure if there is a need for a PR now, but I really suggest adding this in the documentation

**Comment by chfw** [comment]
Good news indeed. I will document it before closing this issue.
