### ISSUE TITLE
PyPI package contains some/broken? pyexcel

### ISSUE THREAD

**Issue by dracos** [pyexcel/pyexcel-io#37]
Hi, the 0.3.4 pyexcel-io package on PyPI appears to contain some/all of pyexcel but different, which means y importing of pyexcel is no longer working. For example, pyexcel/__init__.py is just a one line file in the pyexcel-io package.
Uninstalling/reinstalling pyexcel after pyexcel-io puts it back.

**Comment by chfw** [comment]
you are right. I will push up a quick fix.

**Comment by chfw** [comment]
released a tar.gz file as source distribution. pypi does not allow me to upload the same wheel again.

**Comment by dracos** [comment]
No, you have to bump the version number. Thanks :)

**Comment by chfw** [comment]
pumped the version to 0.3.4.1. now wheel package is in.

**Comment by chfw** [comment]
It was found in https://github.com/pyexcel/pyexcel/issues/89 that some residue folder was left in build directory. When releasing the library, I could have done it in a clean clone and release it.

**Comment by chfw** [comment]
fixed in 0.4.2

**Comment by chfw** [comment]
and pyexcel-io v0.4.0 and v0.4.1 were permanently removed from pypi.
