### ISSUE TITLE
sdist upload missing in latest PyPI release

### ISSUE THREAD

**Issue by ashkulz** [pyexcel/pyexcel-io#38]
The latest PyPI release (`0.3.4.1`) just has a wheel, but not a `sdist upload`. I can understand that it is convenient to have a wheel upload, but this breaks some packaging workflows (I build internal debian packages which assume that the source will be present on PyPI). Please consider including it for the current and future releases as done earlier e.g. see [0.3.3](https://pypi.python.org/pypi/pyexcel-io/0.3.3) which just has the source.

**Comment by chfw** [comment]
uploaded & please check it out.

**Comment by ashkulz** [comment]
Thanks a lot, works now :+1:
