### ISSUE TITLE
csvr does not make the same assumptions about mmap availability as _compact.py

### ISSUE THREAD

**Issue by jakedotio** [pyexcel/pyexcel-io#45]
https://github.com/pyexcel/pyexcel-io/blob/3f1d14ad80cf0aa0357efd9f20a6f22f51737511/pyexcel_io/readers/csvr.py#L234

mmap is not available on Google App Engine - this issue was previously thought fixed with https://github.com/pyexcel/pyexcel-io/issues/41 but I hadn't tried to read a CSV at the time.

Can we check if it's running on App Engine as well as PY27 and above? From the docs, the environment variable SERVER_SOFTWARE will report one of two things when running on App Engine: In the development web server, this value is "Development/X.Y" where "X.Y" is the version of the runtime. When running on App Engine, this value is "Google App Engine/X.Y.Z".

**Comment by chfw** [comment]
I think I will do a try-catch there

**Comment by chfw** [comment]
please try: `pip install https://github.com/pyexcel/pyexcel-io/archive/master.zip`

**Comment by jakedotio** [comment]
The fix resolved the issue. Thank you! Best wishes for happy holidays.
