### ISSUE TITLE
Expose control over Django bulk_save option

### ISSUE THREAD

**Issue by ShaheedHaque** [pyexcel/pyexcel-io#46]
I'm running into an issue with Django's QuerySet.bulk_create() on multi-table inheritance which [might be addressed in some cases](https://code.djangoproject.com/ticket/28821). The use of this feature is controlled using the bulk_save option on [pyexcel_io.database.importers.django.DjangoModelWriter](https://github.com/pyexcel/pyexcel-io/blob/a9bbbc4de7afcde289d745264d5bb115bbc0b8f1/pyexcel_io/database/importers/django.py#L20)...however, this is not exposed by pyexcel_io.database.importers.django.DjangoBookWriter:

>             sheet_writer = DjangoModelWriter(
>                self.__importer, model,
>                batch_size=self._keywords.get('batch_size', None))

A simple patch to address this would be to change that to:

>             sheet_writer = DjangoModelWriter(
>                self.__importer, model,
>                batch_size=self._keywords.get('batch_size', None),
>                bulk_save=self._keywords.get('bulk_save', None))

or (unless there is some reason to limit what is passed?) possibly even:

>             sheet_writer = DjangoModelWriter(
>                self.__importer, model, **self._keywords)

Higher up, the ability to specify bulk_save is present in pyexcel.internal.core.save_sheet and save_book but is not exposed by pyexcel.internal.meta.BookMeta.save_to_django_models. This would need to be trivially addressed too.

FWIW, I'm presently using pyexcel-io 0.5.4, but I see that master (as above) also currently has this issue.

**Comment by chfw** [comment]
I am sorry for the delay. Please try it. I have chosen the first suggestion. Will release it soon.

**Comment by ShaheedHaque** [comment]
Thanks. See my comment on the commit.

**Comment by chfw** [comment]
please take latest pyexcel, pyexcel-io and django-excel.

**Comment by ShaheedHaque** [comment]
I don't see a new package for django-excel? Pypi still seems to be on 0.0.9 which I believe predates the fix. (I do see pyexcel has been bumped to 0.5.7 and pyexcel-io to 0.5.6).

**Comment by chfw** [comment]
Hey, my apologies. I forgot to publish django-excel v0.0.10 to pypi last night. now it is there.

**Comment by ShaheedHaque** [comment]
Thanks, that seems to work nicely.
