### ISSUE TITLE
lml version conflict

### ISSUE THREAD

**Issue by tricoder42** [pyexcel/pyexcel-io#55]
First of all, thank you for a great library!

I tried to update dependencies today using `pipenv update` and I got a version conflict:

```
Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches lml==0.0.1,>=0.0.2
Tried: 0.0.1, 0.0.1, 0.0.2, 0.0.2, 0.0.3, 0.0.3, 0.0.4, 0.0.4
There are incompatible versions in the resolved dependencies.
```

This seems to be related to #53, but I really don't understand from where `==0.0.1` requirement comes from. As a temporary workaround I pinned this library to `==0.5.9`

---

I looked at verbose output of `pipenv lock` and in the first round of dependency resolution, there's this:

```
pyexcel-xls==0.5.8        requires lml==0.0.1, pyexcel-io>=0.5.3, pyexcel-xls==0.5.8, xlrd, xlwt
```

However, `pyexcel-xls` doesn't seem to have a dependency on `lml===0.0.1`. At least I haven't found it in repo.

Any ideas?

**Comment by chfw** [comment]
pyexcel v0.5.9.1 and pyexcel-io 0.5.9 have been upgraded to require lml>=0.0.2.

`pip freez|grep pyexcel` and what are the pyexcel components there?

**Comment by tricoder42** [comment]
I use `pyexcel-xls` only (which has direct dependency to `pyexcel-io`:

```
$ pip freeze | grep pyexcel
pyexcel-io==0.5.9
pyexcel-xls==0.5.8
```
