### ISSUE TITLE
Include tests in source tarballs

### ISSUE THREAD

**Issue by jayvdb** [pyexcel/pyexcel-io#60]

**Comment by jayvdb** [comment]
Also for pyexcel , pyexcel-xls, pyexcel-xlsx being packaged at https://build.opensuse.org/project/show/home:jayvdb:pyexcel

Then the others ... ;-)

**Comment by chfw** [comment]
Thanks for your effort in packaging pyexcel. I will do so at your command.

**Comment by chfw** [comment]
Just did a googling. Emendonca did include  into opensuse, though not the latest nor your standard. 

Anyway thanks for both of you.

**Comment by jayvdb** [comment]
I based my packages on Emendonca's, so their contribution is included in the history.

**Comment by jayvdb** [comment]
fwiw, I have a fairly easy workaround described at https://github.com/openSUSE/py2pack/issues/110 , so this isnt a high priority now.

**Comment by jayvdb** [comment]
For https://github.com/pyexcel/pyexcel , it also needs to include `examples`.

And they all should include `docs` , so doctest can be run

**Comment by chfw** [comment]
Hold on. 0.5.12 did too much.

**Comment by jayvdb** [comment]
Just noting, when doing this for the other pyexcel packages, see https://github.com/pyexcel/pyexcel-io/issues/65
