### ISSUE TITLE
Version 0.5.12 prevents xslx and ods plugin from being loaded

### ISSUE THREAD

**Issue by maximebf** [pyexcel/pyexcel-io#63]
When using this version of pyexcel-io, I get the following error:
`SupportingPluginAvailableButNotInstalled: Please install one of these plugins for write data in 'ods': pyexcel-ods,pyexcel-ods3`

Downgrading to 0.5.11 works again.

**Comment by chfw** [comment]
Yep you are right. Will provide an upgrade the others soon.

**Comment by chfw** [comment]
have now withdrawn 0.5.12.

**Comment by chfw** [comment]
thanks for your prompt report. without your active reporting, I would not have known what crime I have committed. please try 0.5.13, which try to address #60, #61 but does not carry code changes.

**Comment by chfw** [comment]
this has been fixed by later versions.
