### ISSUE TITLE
Any two or more contiguous blank rows are being transformed into a single one

### ISSUE THREAD

**Issue by EPadronU** [pyexcel/pyexcel-io#8]
I will love to know how to fix this. I need to deliver a script to a client today and this is giving me problems.

I'm using pyexcel-io through pyexcel-ods. This behavior is happening when I read a file.

These are the important pieces of code from pyexcel-ods

```py
from pyexcel_io import (
    SheetReaderBase,
    BookReader,
    SheetWriter,
    BookWriter,
    READERS,
    WRITERS,
    isstream,
    load_data as read_data,
    store_data as write_data
)
```

```py
def get_data(afile, file_type=None, **keywords):
    """
    Retrieve all data from incoming file
    """
    if isstream(afile) and file_type is None:
        file_type = 'ods'
    return read_data(afile, file_type=file_type, **keywords)
```

I've tried to replace load_data with get_data and I got the same result. I don't know what to do...

**Comment by chfw** [comment]
It is implemented here: https://github.com/pyexcel/pyexcel-ods/blob/master/pyexcel_ods/__init__.py#L161. I will have a look.

**Comment by EPadronU** [comment]
Thanks.

**Comment by chfw** [comment]
I am sorry for the late reply. Seems the latest code preserves blank rows. I would then close this issue. If I understood incorrectly, please re-open this issue.
